//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("PhieuXuatKho_ID")]
    public partial class ChiTietPhieuXuatKho : DevExpress.Persistent.BaseImpl.BaseObject
    {
        PhieuXuatKho fPhieuXuatKho_ID;
        [Association(@"ChiTietPhieuXuatKhoReferencesPhieuXuatKho")]
        public PhieuXuatKho PhieuXuatKho_ID
        {
            get { return fPhieuXuatKho_ID; }
            set { SetPropertyValue<PhieuXuatKho>(nameof(PhieuXuatKho_ID), ref fPhieuXuatKho_ID, value); }
        }
        HangHoa fHangHoa_ID;
        [Association(@"ChiTietPhieuXuatKhoReferencesHangHoa")]
        public HangHoa HangHoa_ID
        {
            get { return fHangHoa_ID; }
            set { SetPropertyValue<HangHoa>(nameof(HangHoa_ID), ref fHangHoa_ID, value); }
        }
        string fSoLuong;
        public string SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<string>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fDonGia;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),

DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
    }

}
