//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("HoaDon_ID")]
    public partial class ChiTietHoaDon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        HoaDon fHoaDon_ID;
        [Association(@"ChiTietHoaDonReferencesHoaDon")]
        public HoaDon HoaDon_ID
        {
            get { return fHoaDon_ID; }
            set { SetPropertyValue<HoaDon>(nameof(HoaDon_ID), ref fHoaDon_ID, value); }
        }
        HangHoa fHangHoa_ID;
        [Association(@"ChiTietHoaDonReferencesHangHoa")]
        public HangHoa HangHoa_ID
        {
            get { return fHangHoa_ID; }
            set { SetPropertyValue<HangHoa>(nameof(HangHoa_ID), ref fHangHoa_ID, value); }
        }
        string fSoLuong;
        public string SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<string>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fThanhTien;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal ThanhTien
        {
            get { return fThanhTien; }
            set { SetPropertyValue<decimal>(nameof(ThanhTien), ref fThanhTien, value); }
        }
        decimal fDonGia;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
    }

}
