//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("HangHoa_ID")]
    public partial class HangHoa : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHangHoa_ID;
        public string HangHoa_ID
        {
            get { return fHangHoa_ID; }
            set { SetPropertyValue<string>(nameof(HangHoa_ID), ref fHangHoa_ID, value); }
        }
        string fTenHang;
        public string TenHang
        {
            get { return fTenHang; }
            set { SetPropertyValue<string>(nameof(TenHang), ref fTenHang, value); }
        }
        decimal fGiaBan;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<decimal>(nameof(GiaBan), ref fGiaBan, value); }
        }
        decimal fGiaVon;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal GiaVon
        {
            get { return fGiaVon; }
            set { SetPropertyValue<decimal>(nameof(GiaVon), ref fGiaVon, value); }
        }
        string fTonKho;
        public string TonKho
        {
            get { return fTonKho; }
            set { SetPropertyValue<string>(nameof(TonKho), ref fTonKho, value); }
        }
        decimal fDonViTinh;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),

DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal DonViTinh
        {
            get { return fDonViTinh; }
            set { SetPropertyValue<decimal>(nameof(DonViTinh), ref fDonViTinh, value); }
        }
        NhomHang fNhomHang_ID;
        [Association(@"HangHoaReferencesNhomHang")]
        public NhomHang NhomHang_ID
        {
            get { return fNhomHang_ID; }
            set { SetPropertyValue<NhomHang>(nameof(NhomHang_ID), ref fNhomHang_ID, value); }
        }
        string fKho_ID;
        public string Kho_ID
        {
            get { return fKho_ID; }
            set { SetPropertyValue<string>(nameof(Kho_ID), ref fKho_ID, value); }
        }
        NhaCungCap fNhaCungCap_ID;
        [Association(@"HangHoaReferencesNhaCungCap")]
        public NhaCungCap NhaCungCap_ID
        {
            get { return fNhaCungCap_ID; }
            set { SetPropertyValue<NhaCungCap>(nameof(NhaCungCap_ID), ref fNhaCungCap_ID, value); }
        }
        [Association(@"ChiTietHoaDonReferencesHangHoa"), Aggregated]
        public XPCollection<ChiTietHoaDon> ChiTietHoaDons { get { return GetCollection<ChiTietHoaDon>(nameof(ChiTietHoaDons)); } }
        [Association(@"ChiTietPhieuXuatKhoReferencesHangHoa"), Aggregated]
        public XPCollection<ChiTietPhieuXuatKho> ChiTietPhieuXuatKhoes { get { return GetCollection<ChiTietPhieuXuatKho>(nameof(ChiTietPhieuXuatKhoes)); } }
        [Association(@"ChiTietPhieuNhapReferencesHangHoa"), Aggregated]
        public XPCollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get { return GetCollection<ChiTietPhieuNhap>(nameof(ChiTietPhieuNhaps)); } }
    }

}
