//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("HoaDon_ID")]
    public partial class HoaDon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoaDon_ID;
        public string HoaDon_ID
        {
            get { return fHoaDon_ID; }
            set { SetPropertyValue<string>(nameof(HoaDon_ID), ref fHoaDon_ID, value); }
        }
        NhanVien fNhanVien_ID;
        [Association(@"HoaDonReferencesNhanVien")]
        public NhanVien NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        KhachHang fKhachHang_ID;
        [Association(@"HoaDonReferencesKhachHang")]
        public KhachHang KhachHang_ID
        {
            get { return fKhachHang_ID; }
            set { SetPropertyValue<KhachHang>(nameof(KhachHang_ID), ref fKhachHang_ID, value); }
        }
        DateTime fThoiGian;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<DateTime>(nameof(ThoiGian), ref fThoiGian, value); }
        }
        decimal fTongTien;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal TongTien
        {
            get { return fTongTien; }
            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        [Association(@"ChiTietHoaDonReferencesHoaDon"), Aggregated]
        public XPCollection<ChiTietHoaDon> ChiTietHoaDons { get { return GetCollection<ChiTietHoaDon>(nameof(ChiTietHoaDons)); } }
    }

}
