//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("KhachHang_ID")]
    public partial class KhachHang : DevExpress.Persistent.BaseImpl.BaseObject
    {
        KhachHang fKhachHang_ID;
        public KhachHang KhachHang_ID
        {
            get { return fKhachHang_ID; }
            set { SetPropertyValue<KhachHang>(nameof(KhachHang_ID), ref fKhachHang_ID, value); }
        }
        string fTênKhachHang;
        public string TênKhachHang
        {
            get { return fTênKhachHang; }
            set { SetPropertyValue<string>(nameof(TênKhachHang), ref fTênKhachHang, value); }
        }
        string fSDT;
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        [Association(@"HoaDonReferencesKhachHang"), Aggregated]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
    }

}
