//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("NhaCungCap_ID")]
    public partial class NhaCungCap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhaCungCap_ID;
        public string NhaCungCap_ID
        {
            get { return fNhaCungCap_ID; }
            set { SetPropertyValue<string>(nameof(NhaCungCap_ID), ref fNhaCungCap_ID, value); }
        }
        string fTen;
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>(nameof(Ten), ref fTen, value); }
        }
        string fSDT;
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>(nameof(SDT), ref fSDT, value); }
        }
        string fMaSoThue;
        public string MaSoThue
        {
            get { return fMaSoThue; }
            set { SetPropertyValue<string>(nameof(MaSoThue), ref fMaSoThue, value); }
        }
        [Association(@"HangHoaReferencesNhaCungCap"), Aggregated]
        public XPCollection<HangHoa> HangHoas { get { return GetCollection<HangHoa>(nameof(HangHoas)); } }
        [Association(@"PhieuChiReferencesNhaCungCap"), Aggregated]
        public XPCollection<PhieuChi> PhieuChis { get { return GetCollection<PhieuChi>(nameof(PhieuChis)); } }
    }

}
