//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("NhanVien_ID")]
    public partial class NhanVien : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhanVien_ID;
        public string NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<string>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fMatKhau;
        public string MatKhau
        {
            get { return fMatKhau; }
            set { SetPropertyValue<string>(nameof(MatKhau), ref fMatKhau, value); }
        }
        [Association(@"PhieuLuongReferencesNhanVien"), Aggregated]
        public XPCollection<PhieuLuong> PhieuLuongs { get { return GetCollection<PhieuLuong>(nameof(PhieuLuongs)); } }
        [Association(@"PhieuChiReferencesNhanVien"), Aggregated]
        public XPCollection<PhieuChi> PhieuChis { get { return GetCollection<PhieuChi>(nameof(PhieuChis)); } }
        [Association(@"HoaDonReferencesNhanVien"), Aggregated]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
        [Association(@"PhieuNhapReferencesNhanVien"), Aggregated]
        public XPCollection<PhieuNhap> PhieuNhaps { get { return GetCollection<PhieuNhap>(nameof(PhieuNhaps)); } }
    }

}
