//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("NhomHang_ID")]
    public partial class NhomHang : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhomHang_ID;
        public string NhomHang_ID
        {
            get { return fNhomHang_ID; }
            set { SetPropertyValue<string>(nameof(NhomHang_ID), ref fNhomHang_ID, value); }
        }
        string fTenNhomHang;
        public string TenNhomHang
        {
            get { return fTenNhomHang; }
            set { SetPropertyValue<string>(nameof(TenNhomHang), ref fTenNhomHang, value); }
        }
        [Association(@"HangHoaReferencesNhomHang"), Aggregated]
        public XPCollection<HangHoa> HangHoas { get { return GetCollection<HangHoa>(nameof(HangHoas)); } }
    }

}
