//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("PhieuXuatKho_ID")]
    public partial class PhieuXXuatKho : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fPhieuXuatKho_ID;
        public string PhieuXuatKho_ID
        {
            get { return fPhieuXuatKho_ID; }
            set { SetPropertyValue<string>(nameof(PhieuXuatKho_ID), ref fPhieuXuatKho_ID, value); }
        }
        string fNhanVien_ID;
        public string NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<string>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        string fKho_ID;
        public string Kho_ID
        {
            get { return fKho_ID; }
            set { SetPropertyValue<string>(nameof(Kho_ID), ref fKho_ID, value); }
        }
        DateTime fThoiGian;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<DateTime>(nameof(ThoiGian), ref fThoiGian, value); }
        }
    }

}
