//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("PhieuLuong_ID")]
    public partial class PhieuLuong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fPhieuLuong_ID;
        [Size(30)]
        public string PhieuLuong_ID
        {
            get { return fPhieuLuong_ID; }
            set { SetPropertyValue<string>(nameof(PhieuLuong_ID), ref fPhieuLuong_ID, value); }
        }
        NhanVien fNhanVien_ID;
        [Size(30)]
        [Association(@"PhieuLuongReferencesNhanVien")]
        public NhanVien NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        decimal fLuongCoBan;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal LuongCoBan
        {
            get { return fLuongCoBan; }
            set { SetPropertyValue<decimal>(nameof(LuongCoBan), ref fLuongCoBan, value); }
        }
        short fSoGio;
        public short SoGio
        {
            get { return fSoGio; }
            set { SetPropertyValue<short>(nameof(SoGio), ref fSoGio, value); }
        }
        decimal fHoaHong;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal HoaHong
        {
            get { return fHoaHong; }
            set { SetPropertyValue<decimal>(nameof(HoaHong), ref fHoaHong, value); }
        }
        short fThanhTien;
        public short ThanhTien
        {
            get { return fThanhTien; }
            set { SetPropertyValue<short>(nameof(ThanhTien), ref fThanhTien, value); }
        }
        DateTime fThoiGian;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<DateTime>(nameof(ThoiGian), ref fThoiGian, value); }
        }
    }

}
