//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("PhieuNhap_ID")]
    public partial class PhieuNhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fPhieuNhap_ID;
        public string PhieuNhap_ID
        {
            get { return fPhieuNhap_ID; }
            set { SetPropertyValue<string>(nameof(PhieuNhap_ID), ref fPhieuNhap_ID, value); }
        }
        NhanVien fNhanVien_ID;
        [Association(@"PhieuNhapReferencesNhanVien")]
        public NhanVien NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        string fNhaCungCap_ID;
        public string NhaCungCap_ID
        {
            get { return fNhaCungCap_ID; }
            set { SetPropertyValue<string>(nameof(NhaCungCap_ID), ref fNhaCungCap_ID, value); }
        }
        DateTime fThoiGian;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<DateTime>(nameof(ThoiGian), ref fThoiGian, value); }
        }
        [Association(@"ChiTietPhieuNhapReferencesPhieuNhap"), Aggregated]
        public XPCollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get { return GetCollection<ChiTietPhieuNhap>(nameof(ChiTietPhieuNhaps)); } }
    }

}
