//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Project_CS403U_Group2_QLBanGiay.Module.BusinessObjects.QLBanGiay
{

    [DefaultProperty("PhieuChi_ID")]
    public partial class PhieuChi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fPhieuChi_ID;
        public string PhieuChi_ID
        {
            get { return fPhieuChi_ID; }
            set { SetPropertyValue<string>(nameof(PhieuChi_ID), ref fPhieuChi_ID, value); }
        }
        NhanVien fNhanVien_ID;
        [Association(@"PhieuChiReferencesNhanVien")]
        public NhanVien NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<NhanVien>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        NhaCungCap fNhaCungCap_ID;
        [Association(@"PhieuChiReferencesNhaCungCap")]
        public NhaCungCap NhaCungCap_ID
        {
            get { return fNhaCungCap_ID; }
            set { SetPropertyValue<NhaCungCap>(nameof(NhaCungCap_ID), ref fNhaCungCap_ID, value); }
        }
        decimal fGiaTri;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal GiaTri
        {
            get { return fGiaTri; }
            set { SetPropertyValue<decimal>(nameof(GiaTri), ref fGiaTri, value); }
        }
        DateTime fThoiGian;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<DateTime>(nameof(ThoiGian), ref fThoiGian, value); }
        }
    }

}
